global_costmap:
  global_frame: /map
  robot_base_frame: /robot0
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false
  transform_tolerance: 5.0
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}