local_costmap:
  global_frame: /map
  robot_base_frame: /robot0
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.02
  transform_tolerance: 2.0
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}